-- Applicant permission and review lifecycle on the real disposable PostgreSQL/RLS harness.
begin;
create function pg_temp.assert_true(condition boolean,label text) returns text language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAIL: %',label; end if; return 'PASS: '||label; end $$;
create function pg_temp.assert_rejected(statement text,pattern text,label text) returns text language plpgsql as $$ begin begin execute statement; exception when others then if sqlerrm~pattern then return 'PASS: '||label; end if; raise exception 'FAIL: % (unexpected error %)',label,sqlerrm; end; raise exception 'FAIL: % (unexpected success)',label; end $$;
select pg_temp.assert_true(not has_function_privilege('anon','public.request_driver_application()','EXECUTE'),'anonymous cannot bootstrap application');
select pg_temp.assert_true(not has_function_privilege('authenticated','private.lock_driver_application()','EXECUTE'),'private application lock helper is not an exposed privilege shortcut');
select set_config('test.application_history',(select count(*)::text from public.ride_requests where passenger_id='10000000-0000-4000-8000-000000000001'),true);
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.request_driver_application();
select public.request_driver_application();
select set_config('test.application_id',(select id::text from public.driver_profiles where user_id=auth.uid()),true);
select pg_temp.assert_true((select role='passenger' from public.profiles where id=auth.uid()),'existing passenger retains passenger role while applying');
select pg_temp.assert_true((select count(*)=1 and bool_and(verification_status='pending' and not online) from public.driver_profiles where user_id=auth.uid()),'repeated explicit application creates exactly one own unapproved draft');
select pg_temp.assert_true((select count(*)::text=current_setting('test.application_history') from public.ride_requests where passenger_id=auth.uid()),'applicant keeps same user and all passenger ride history');
select pg_temp.assert_true(public.current_user_is_driver_applicant(true),'passenger draft has narrow editable-applicant access');
select pg_temp.assert_rejected($q$update public.profiles set role='driver' where id=auth.uid()$q$,'permission denied','applicant cannot grant self operational role');
select pg_temp.assert_rejected($q$update public.driver_profiles set verification_status='verified' where user_id=auth.uid()$q$,'permission denied','applicant cannot self-approve by direct database update');
select pg_temp.assert_rejected($q$insert into public.driver_profiles(user_id,preferred_area) values(auth.uid(),'Forged duplicate')$q$,'permission denied','application bootstrap cannot be bypassed with direct table insert');
select pg_temp.assert_rejected($q$select public.set_driver_availability(true,14.55,121.05)$q$,'driver role','passenger applicant cannot become dispatch-available');
select pg_temp.assert_rejected($q$select public.accept_ride_offer(gen_random_uuid())$q$,'driver role','passenger applicant cannot accept trips');
select pg_temp.assert_rejected($q$select public.advance_trip('40000000-0000-4000-8000-000000000002','heading')$q$,'driver role','passenger applicant cannot mutate operational trips');
select pg_temp.assert_rejected($q$select public.admin_review_driver(current_setting('test.application_id')::uuid,'verified')$q$,'operations role','applicant cannot approve through review RPC');
select pg_temp.assert_rejected($q$select public.submit_driver_onboarding()$q$,'personal details','incomplete draft cannot look submitted');
select pg_temp.assert_true(public.save_driver_profile('09170000001','Fictional Metro Manila')::text=current_setting('test.application_id'),'passenger applicant can save own personal application fields');
select set_config('test.application_vehicle',public.save_driver_vehicle('sedan','Fictional','Applicant Car',2025,'White','QA-APPLICATION-ONLY',4)::text,true);
select pg_temp.assert_true((select owner_user_id=auth.uid() and not verified from public.vehicles where id=current_setting('test.application_vehicle')::uuid),'applicant vehicle belongs to same account and starts unverified');
select pg_temp.assert_rejected($q$select public.save_driver_vehicle('sedan','Forged','Other Owner',2025,'Black','QA-FORGED-ONLY',4,'30000000-0000-4000-8000-000000000002')$q$,'vehicle not found','applicant cannot change another owner vehicle');
insert into storage.objects(bucket_id,name,owner_id) values('driver-documents','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',auth.uid()::text),('vehicle-documents','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',auth.uid()::text);
select public.record_driver_document('drivers_license','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',current_date+365);
select public.record_vehicle_document(current_setting('test.application_vehicle')::uuid,'registration','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',current_date+365);
select pg_temp.assert_true((select count(*)=2 from storage.objects where name='10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf'),'pending passenger applicant can upload and read own private document objects');
select pg_temp.assert_rejected($q$insert into storage.objects(bucket_id,name,owner_id) values('driver-documents','10000000-0000-4000-8000-000000000002/QA-CROSS-USER.pdf',auth.uid()::text)$q$,'row-level security','applicant cannot upload into another user private folder');
select pg_temp.assert_rejected($q$select public.record_driver_document('drivers_license','10000000-0000-4000-8000-000000000002/DEMO-ONLY.pdf',current_date+365)$q$,'invalid storage path','applicant cannot attach another user document');
select pg_temp.assert_rejected($q$update public.driver_documents set reviewed_by=auth.uid(),reviewed_at=now(),verification_status='verified'$q$,'permission denied','applicant cannot forge reviewer fields');
delete from storage.objects where name='10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf';
select pg_temp.assert_true((select count(*)=2 from storage.objects where name='10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf'),'referenced private objects cannot be deleted by applicant');
select public.submit_driver_onboarding();
select public.submit_driver_onboarding();
select public.request_driver_application();
select pg_temp.assert_true((select verification_status='under_review' and not online from public.driver_profiles where id=current_setting('test.application_id')::uuid),'submit and replay retain one locked under-review application');
select pg_temp.assert_true((select role='passenger' from public.profiles where id=auth.uid()),'submitted applicant still has no operational driver role');
select pg_temp.assert_rejected($q$select public.save_driver_profile('09170000002','Forbidden review edit')$q$,'locked','submitted personal data cannot be silently rewritten');
select pg_temp.assert_rejected($q$select public.record_driver_document('drivers_license','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',current_date+365)$q$,'locked','submitted documents cannot be silently replaced');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000010',true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.driver_documents where driver_id=current_setting('test.application_id')::uuid),'unrelated user cannot read applicant documents');
select pg_temp.assert_true((select count(*)=0 from storage.objects where name='10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf'),'unrelated user cannot read private application objects');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=1 from public.driver_profiles where id=current_setting('test.application_id')::uuid and verification_status='under_review'),'submitted application appears in existing operations review query');
select public.admin_review_driver(current_setting('test.application_id')::uuid,'rejected','Please replace the fictional unreadable license');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.request_driver_application();
select pg_temp.assert_true((select verification_status='rejected' from public.driver_profiles where id=current_setting('test.application_id')::uuid),'application replay cannot clear a rejection');
select pg_temp.assert_true((select rejection_reason='Please replace the fictional unreadable license' from public.driver_documents where driver_id=current_setting('test.application_id')::uuid),'applicant sees own actionable correction reason');
select public.record_driver_document('drivers_license','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',current_date+365);
select public.record_vehicle_document(current_setting('test.application_vehicle')::uuid,'registration','10000000-0000-4000-8000-000000000001/QA-APPLICATION.pdf',current_date+365);
select public.submit_driver_onboarding();
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.admin_review_driver(current_setting('test.application_id')::uuid,'verified')$q$,'finish or cancel active passenger bookings','approval waits for active passenger rides to finish instead of stranding the account');
select pg_temp.assert_true((select role='passenger' from public.profiles where id='10000000-0000-4000-8000-000000000001'),'blocked approval retains passenger access and under-review application');
reset role;
-- Owner-only fictional fixture cleanup, retaining rows/history; no existing backend writes.
update public.ride_requests set status='operator_cancelled' where passenger_id='10000000-0000-4000-8000-000000000001' and status in ('draft','requested','searching','offered','assigned','driver_en_route','driver_arrived','trip_started');
set local role authenticated;
select public.admin_review_driver(current_setting('test.application_id')::uuid,'verified');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.request_driver_application();
select pg_temp.assert_true((select role='driver' from public.profiles where id=auth.uid()),'only trusted approval grants existing driver operational role');
select pg_temp.assert_true((select verification_status='verified' and not online from public.driver_profiles where id=current_setting('test.application_id')::uuid),'bootstrap replay does not downgrade approved application or turn it online');
select pg_temp.assert_true((select count(*)::text=current_setting('test.application_history') from public.ride_requests where passenger_id=auth.uid()),'approval retains historical passenger ride ownership');
select pg_temp.assert_rejected($q$select public.save_driver_profile('09170000002','Approved bypass edit')$q$,'locked','approved application cannot be reset through applicant editing');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select public.admin_review_driver(current_setting('test.application_id')::uuid,'suspended','Fictional restricted status');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.request_driver_application();
select pg_temp.assert_true((select verification_status='suspended' and not online from public.driver_profiles where id=current_setting('test.application_id')::uuid),'repeated apply cannot bypass suspended application');
select pg_temp.assert_rejected($q$select public.save_driver_profile('09170000002','Suspension bypass edit')$q$,'locked','suspended application edits denied');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select public.admin_review_driver(current_setting('test.application_id')::uuid,'verified');
select pg_temp.assert_true((select verification_status='verified' and not online from public.driver_profiles where id=current_setting('test.application_id')::uuid),'trusted admin can reinstate suspended driver after the existing eligibility checks');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
update public.profiles set account_status='suspended' where id='10000000-0000-4000-8000-000000000001';
set local role authenticated;
select pg_temp.assert_rejected($q$select public.request_driver_application()$q$,'active passenger or driver','restricted account cannot bootstrap a new application');
reset role;
rollback;
