-- Real role/RLS and transaction tests; only run inside the disposable harness.
begin;
create function pg_temp.assert_true(p_condition boolean,p_label text) returns text language plpgsql as $$ begin if p_condition is distinct from true then raise exception 'FAIL: %',p_label; end if; return 'PASS: '||p_label; end $$;
create function pg_temp.assert_rejected(p_sql text,p_pattern text,p_label text) returns text language plpgsql as $$ begin begin execute p_sql; exception when others then if sqlerrm ~ p_pattern then return 'PASS: '||p_label; end if; raise exception 'FAIL: % (unexpected error %)',p_label,sqlerrm; end; raise exception 'FAIL: % (operation succeeded)',p_label; end $$;
update private.release_environment set environment='pilot';
-- Intentionally leave legacy demo flags true: private environment must override them.
select pg_temp.assert_true(not public.rc1_demo_allowed(),'pilot ignores legacy enabled demo flags');
select pg_temp.assert_true(not has_function_privilege('anon','public.create_transport_request(jsonb)','EXECUTE'),'anonymous cannot create RC1 bookings');
select pg_temp.assert_true(not has_table_privilege('authenticated','private.release_environment','UPDATE'),'client cannot change deployment environment');
select pg_temp.assert_true(not has_table_privilege('authenticated','public.ride_quotes','UPDATE'),'quote history cannot be rewritten by clients');
select pg_temp.assert_true(not has_table_privilege('authenticated','public.cash_collection_events','UPDATE'),'cash history cannot be rewritten by clients');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.admin_update_config('{"demo_mode":true,"mock_payment_enabled":true}')$q$,'isolated demo','admin cannot enable mock mode in pilot');
select pg_temp.assert_rejected($q$select public.record_mock_payment_event('40000000-0000-4000-8000-000000000001','pilot-mock','paid')$q$,'explicit demo','pilot rejects simulated payment even with legacy flags');
select pg_temp.assert_rejected($q$select public.admin_update_config('{"driver_commission_percent":1}')$q$,'commission policy','pilot commission cannot be silently changed');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select set_config('test.rc1_payload',jsonb_build_object('client_request_id','88000000-0000-4000-8000-000000000001','pickup_address','Fictional manual-review pickup landmark','dropoff_address','Fictional manual-review dropoff landmark','scheduled_at',to_char((now()+interval '20 days') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"'),'vehicle_type','sedan','service_type','scheduled','passenger_count',2,'estimated_fare',1,'driver_earnings',999999,'payment_status','paid')::text,true);
select set_config('test.rc1_ride',public.create_transport_request(current_setting('test.rc1_payload')::jsonb)::text,true);
select pg_temp.assert_true(public.create_transport_request(current_setting('test.rc1_payload')::jsonb)::text=current_setting('test.rc1_ride'),'same operation reconciles identical booking after lost response');
select pg_temp.assert_rejected($q$select public.create_transport_request(current_setting('test.rc1_payload')::jsonb||'{"pickup_address":"Changed pickup"}')$q$,'payload conflict','same operation with changed payload rejected');
select pg_temp.assert_true((select quote_status='pending_review' and gross_fare is null and estimated_duration_seconds is null and pickup_location is null and dropoff_location is null from public.ride_requests where id=current_setting('test.rc1_ride')::uuid),'real address-only booking has no fabricated fare, route or location');
select pg_temp.assert_rejected($q$select public.create_transport_request(current_setting('test.rc1_payload')::jsonb||jsonb_build_object('client_request_id',gen_random_uuid(),'scheduled_at','2026-09-09T12:00:00'))$q$,'explicit timezone','ambiguous local timestamp rejected');
select pg_temp.assert_rejected($q$select public.create_transport_request(current_setting('test.rc1_payload')::jsonb||jsonb_build_object('client_request_id',gen_random_uuid(),'scheduled_at',to_char((now()-interval '1 minute') at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS"Z"')))$q$,'30 minutes','past schedule rejected on server');
select pg_temp.assert_rejected($q$select public.admin_review_ride_quote(current_setting('test.rc1_ride')::uuid,0,1000,3600,'Fictional quote')$q$,'operations role','passenger cannot set reviewed fare');
select pg_temp.assert_rejected($q$select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,gen_random_uuid(),'reported',1000,'Forged collection')$q$,'assigned driver','passenger cannot forge cash collection');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000010',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.accept_ride_quote(current_setting('test.rc1_ride')::uuid,1)$q$,'own booking','outsider cannot accept passenger quote');
select pg_temp.assert_true((select count(*)=0 from public.ride_quotes where ride_request_id=current_setting('test.rc1_ride')::uuid),'outsider cannot read quote');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_true(public.admin_review_ride_quote(current_setting('test.rc1_ride')::uuid,0,1234.56,3600,'Reviewed fictional route, tolls included')=1,'operator creates versioned PHP quote');
select pg_temp.assert_rejected($q$select public.admin_review_ride_quote(current_setting('test.rc1_ride')::uuid,0,2000,3600,'Stale operator edit')$q$,'version conflict','stale operator quote revision rejected');
select pg_temp.assert_rejected($q$select public.admin_review_ride_quote(current_setting('test.rc1_ride')::uuid,1,10.001,3600,'Invalid fractional cent')$q$,'amount','fractional-cent manual amount rejected');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select public.accept_ride_quote(current_setting('test.rc1_ride')::uuid,1);
select public.accept_ride_quote(current_setting('test.rc1_ride')::uuid,1);
select pg_temp.assert_true((select quote_status='accepted' and gross_fare=1234.56 and driver_earnings=1234.56 and platform_commission=0 from public.ride_requests where id=current_setting('test.rc1_ride')::uuid),'accepted quote and zero commission are authoritative');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select public.admin_set_release_controls(true,true,true,'Fictional pause test');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.create_transport_request(current_setting('test.rc1_payload')::jsonb||jsonb_build_object('client_request_id',gen_random_uuid()))$q$,'paused','server pause blocks new bookings');
select pg_temp.assert_true(public.create_transport_request(current_setting('test.rc1_payload')::jsonb)::text=current_setting('test.rc1_ride'),'pause still permits recovery of existing operation');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.rc1_manual_assign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002',0,'Stale dispatch attempt')$q$,'version|accepted quote','stale manual dispatch version rejected');
select public.rc1_manual_assign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002',1,'Fictional reviewed schedule and driver assignment');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'heading')$q$,'reconfirmation','manual assignment requires explicit driver reconfirmation');
select public.confirm_ride_assignment(current_setting('test.rc1_ride')::uuid);
reset role;
do $$ begin perform set_config('test.pre_reassignment_hash',(select trip_pin_hash from public.trips where ride_request_id=current_setting('test.rc1_ride')::uuid),true); end $$;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_true(public.rc1_reassign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000009','30000000-0000-4000-8000-000000000009',1,'Fictional replacement driver confirmation')=2,'before-heading reassignment increments assignment version');
select pg_temp.assert_true((select driver_id='20000000-0000-4000-8000-000000000009' and confirmed_at is null from public.ride_assignments where ride_request_id=current_setting('test.rc1_ride')::uuid),'reassignment changes driver and requires new reconfirmation');
select pg_temp.assert_rejected($q$select public.rc1_reassign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002',1,'Stale reassignment attempt')$q$,'version conflict','stale assignment version rejected');
reset role;
select pg_temp.assert_true((select trip_pin_hash<>current_setting('test.pre_reassignment_hash') from public.trips where ride_request_id=current_setting('test.rc1_ride')::uuid),'reassignment regenerates protected PIN credentials');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'heading')$q$,'assigned verified driver','previous driver cannot advance reassigned ride');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_true(public.rc1_reassign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000002','30000000-0000-4000-8000-000000000002',2,'Fictional driver restored before departure')=3,'current-version reassignment can recover before departure');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select public.confirm_ride_assignment(current_setting('test.rc1_ride')::uuid);
select pg_temp.assert_true(public.advance_trip(current_setting('test.rc1_ride')::uuid,'heading')='driver_en_route','confirmed ride progresses despite new-booking pause');
reset role;
update public.driver_documents set expires_on=current_date-1 where driver_id='20000000-0000-4000-8000-000000000002';
set local role authenticated;
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'arrived')$q$,'no longer eligible','expired license rechecked after assignment');
reset role;
update public.driver_documents set expires_on=current_date+365 where driver_id='20000000-0000-4000-8000-000000000002';
set local role authenticated;
select public.advance_trip(current_setting('test.rc1_ride')::uuid,'arrived');
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','000000')$q$,'too early','cannot start scheduled ride early');
reset role;
-- Advance only the fictional test schedule; production callers have no write grant.
select pg_temp.assert_rejected($q$update public.ride_requests set gross_fare=1 where id=current_setting('test.rc1_ride')::uuid$q$,'immutable','even privileged accidental assigned-fare mutation rejected');
-- Clock advancement fixture only: pause the owner-only immutability trigger around schedule time travel.
alter table public.ride_requests disable trigger guard_accepted_fare;
update public.ride_requests set scheduled_at=now()-interval '1 minute' where id=current_setting('test.rc1_ride')::uuid;
alter table public.ride_requests enable trigger guard_accepted_fare;
do $$ begin perform set_config('test.rc1_pin',(select pin from private.trip_secrets where ride_request_id=current_setting('test.rc1_ride')::uuid),true); end $$;
set local role authenticated;
select pg_temp.assert_true(public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','wrong')='driver_arrived','wrong PIN leaves authoritative state unchanged');
select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','wrong');
select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','wrong');
select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','wrong');
select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start','wrong');
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start',current_setting('test.rc1_pin'))$q$,'temporarily locked','five wrong PIN attempts lock even correct PIN');
reset role;
select pg_temp.assert_true((select failed_attempts=5 and locked_until>now() from private.trip_secrets where ride_request_id=current_setting('test.rc1_ride')::uuid),'PIN failure counters persist');
update private.trip_secrets set locked_until=now()-interval '1 second' where ride_request_id=current_setting('test.rc1_ride')::uuid;
set local role authenticated;
select pg_temp.assert_true(public.advance_trip(current_setting('test.rc1_ride')::uuid,'start',current_setting('test.rc1_pin'))='trip_started','correct PIN starts after lock expires');
select pg_temp.assert_rejected($q$select public.advance_trip(current_setting('test.rc1_ride')::uuid,'start',current_setting('test.rc1_pin'))$q$,'replay','PIN cannot be replayed after start');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select pg_temp.assert_rejected($q$select public.rc1_reassign_ride(current_setting('test.rc1_ride')::uuid,'20000000-0000-4000-8000-000000000009','30000000-0000-4000-8000-000000000009',3,'Unsafe in-progress reassignment')$q$,'before heading','in-progress passenger trip cannot be reassigned');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
set local role authenticated;
select pg_temp.assert_true(public.advance_trip(current_setting('test.rc1_ride')::uuid,'complete')='trip_completed','manual scheduled ride completes');
select pg_temp.assert_true(public.advance_trip(current_setting('test.rc1_ride')::uuid,'complete')='trip_completed','completion replay reconciles state');
select pg_temp.assert_true((select count(*)=1 from public.payments where ride_request_id=current_setting('test.rc1_ride')::uuid and status='pending' and provider='cash'),'completed trip remains unpaid with one cash record');
select pg_temp.assert_rejected($q$select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,gen_random_uuid(),'reconciled',1234.56,'Driver self reconciliation')$q$,'operations role','driver cannot reconcile own collection');
select set_config('test.rc1_collection',public.record_cash_collection(current_setting('test.rc1_ride')::uuid,'88000000-0000-4000-8000-000000000002','reported',1234.56,'Fictional cash received')::text,true);
select pg_temp.assert_true(public.record_cash_collection(current_setting('test.rc1_ride')::uuid,'88000000-0000-4000-8000-000000000002','reported',1234.56,'Fictional cash received')::text=current_setting('test.rc1_collection'),'cash report replay returns same event');
select pg_temp.assert_rejected($q$select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,'88000000-0000-4000-8000-000000000002','reported',1,'Changed collection')$q$,'payload conflict','cash operation conflict rejected');
select pg_temp.assert_rejected($q$select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,gen_random_uuid(),'reported',1234.56,'Duplicate new operation')$q$,'already recorded','different operation cannot double-record same collection');
select pg_temp.assert_true((select status='pending' from public.payments where ride_request_id=current_setting('test.rc1_ride')::uuid),'driver cash report is not reconciliation');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000004',true);
set local role authenticated;
select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,'88000000-0000-4000-8000-000000000003','reconciled',1234.56,'Fictional operator reconciliation');
select public.record_cash_collection(current_setting('test.rc1_ride')::uuid,'88000000-0000-4000-8000-000000000003','reconciled',1234.56,'Fictional operator reconciliation');
select pg_temp.assert_true((select status='paid' and provider='cash' from public.payments where ride_request_id=current_setting('test.rc1_ride')::uuid),'operator reconciles reported cash without gateway claim');
select pg_temp.assert_true((select count(*)=2 from public.cash_collection_events where ride_request_id=current_setting('test.rc1_ride')::uuid),'report and reconciliation create exactly two immutable events');
select pg_temp.assert_true((select final_fare=1234.56 and driver_earnings=1234.56 and platform_commission=0 from public.trips where ride_request_id=current_setting('test.rc1_ride')::uuid),'completion preserves agreed PHP fare and earnings');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000010',true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.cash_collection_events where ride_request_id=current_setting('test.rc1_ride')::uuid),'outsider cannot read collection history');
select set_config('test.deletion',public.request_account_deletion('Fictional privacy request')::text,true);
select pg_temp.assert_true(public.request_account_deletion('Fictional privacy request')::text=current_setting('test.deletion'),'account deletion request retries create one open request');
select pg_temp.assert_true((select user_id=auth.uid() and status='requested' from public.account_deletion_requests where id=current_setting('test.deletion')::uuid),'deletion request derives owner from authenticated identity');
select pg_temp.assert_rejected($q$delete from public.profiles where id=auth.uid()$q$,'permission denied','client cannot directly erase account and retained transaction records');
select pg_temp.assert_rejected($q$update public.account_deletion_requests set status='completed' where id=current_setting('test.deletion')::uuid$q$,'permission denied','client cannot mark deletion fulfilled');
reset role;
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.account_deletion_requests where id=current_setting('test.deletion')::uuid),'other passenger cannot read private deletion reason');
reset role;
rollback;
