import { Dashboard,DashboardCard } from '@/components/dashboard';
import { CopyLink } from '@/components/copy-link';
import { SubmitButton } from '@/components/submit-button';
import { requireProfile } from '@/lib/auth/session';
import { createClient } from '@/lib/supabase/server';
import { createReferral,redeemReferral,reviewReferral } from './actions';
export default async function ReferralsPage({searchParams}:{searchParams:Promise<{code?:string;error?:string;message?:string}>}){
 const profile=await requireProfile();const query=await searchParams;const client=await createClient();const [codes,events]=await Promise.all([client.from('referral_codes').select('id,code,referral_type,organization_id'),client.from('referral_events').select('id,referral_code_id,referred_user_id,status,created_at').order('created_at',{ascending:false}).limit(100)]);if(codes.error||events.error)throw new Error('Referral records unavailable.');
 return <Dashboard eyebrow="Grow the network" title="Referral links" description="Invite riders, drivers and business partners. Rewards require manual review and never trigger an automatic payout.">{query.error&&<p role="alert">{query.error}</p>}{query.message&&<p role="status">{query.message}</p>}{codes.data?.map(code=><DashboardCard key={code.id} title={`${code.referral_type} referral`}><CopyLink path={`/referrals?code=${code.code}`} /><p>{events.data?.filter(event=>event.referral_code_id===code.id&&event.status==='signup').length} signups recorded</p><small>{code.id}</small></DashboardCard>)}<DashboardCard title="Create referral link"><form action={createReferral} className="compact-form"><label>Referral type<select name="type"><option value="passenger">Passenger</option><option value="driver">Driver</option><option value="partner">Partner</option></select></label><label>Business account ID (optional)<input name="organization_id" /></label><SubmitButton pendingLabel="Creating…">Create link</SubmitButton></form></DashboardCard><DashboardCard title="Record an invitation"><form action={redeemReferral} className="compact-form"><label>Referral code<input name="code" defaultValue={query.code??''} required /></label><SubmitButton pendingLabel="Recording…">Use referral code</SubmitButton></form></DashboardCard>
 <section className="dashboard-wide"><h2>Referral activity</h2>{events.data?.length?<div className="table-scroll"><table><thead><tr><th>Status</th><th>Referred account</th><th>Date</th></tr></thead><tbody>{events.data.map(event=><tr key={event.id}><td>{event.status.replaceAll('_',' ')}</td><td>{event.referred_user_id??'Link created'}</td><td>{new Date(event.created_at).toLocaleDateString('en-PH',{timeZone:'Asia/Manila'})}</td></tr>)}</tbody></table></div>:<p>No referral activity yet.</p>}</section>
 {profile.role==='admin'&&<DashboardCard title="Review referral qualification or reward"><form action={reviewReferral} className="compact-form"><label>Referral code ID<input name="code_id" required /></label><label>Referred user ID<input name="user_id" required /></label><label>Decision<select name="status">{['qualified_activity','reward_pending','reward_approved','reward_rejected'].map(status=><option key={status}>{status}</option>)}</select></label><label>Review note<textarea name="note" required /></label><SubmitButton pendingLabel="Saving review…">Save review</SubmitButton></form></DashboardCard>}</Dashboard>;
}
