import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { Dashboard, DashboardCard } from '@/components/dashboard';
import { ConfirmForm } from '@/components/confirm-form';
import { SubmitButton } from '@/components/submit-button';
import { requireRole } from '@/lib/auth/session';
import { createClient } from '@/lib/supabase/server';
import { dateTime, type Plan, type Subscription, type Organization } from '@/lib/operations/data';
import { activateBackup, manageSubscription, resolveSafety, reviewDriver, setBackup, simulatePayment, updateConfiguration } from './actions';
export default async function OperationsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  await requireRole('admin');
  const client = await createClient();
  const alerts = await searchParams;
  const [rides, drivers, orgs, subscriptions, plans, config, backups, safety, audits] = await Promise.all([
    client.from('ride_requests').select('id,pickup_address,dropoff_address,scheduled_at,status').in('status', ['requested','searching','offered','assigned','driver_en_route','driver_arrived','trip_started','no_show']).order('scheduled_at').limit(100),
    client.from('driver_profiles').select('id,user_id,verification_status,online').order('created_at').limit(100),
    client.from('organizations').select('id,kind,name,owner_user_id,partner_type').returns<Organization[]>(),
    client.from('organization_subscriptions').select('id,organization_id,plan_id,status,expires_at,billing_status').returns<Subscription[]>(),
    client.from('subscription_plans').select('id,audience,display_name,features,monthly_price_php').eq('active',true).returns<Plan[]>(),
    client.from('app_config').select('*').single(),
    client.from('backup_assignments').select('id,ride_request_id,driver_id,vehicle_id,status').eq('status','ready'),
    client.from('safety_reports').select('id,ride_request_id,category,details,status,created_at').neq('status','resolved').order('created_at'),
    client.from('audit_events').select('id,action,entity_type,entity_id,created_at').order('created_at',{ascending:false}).limit(30),
  ]);
  if ([rides,drivers,orgs,subscriptions,plans,config,backups,safety,audits].some(result => result.error)) throw new Error('Operations records could not be loaded. Check the backend migration and your administrator access.');
  const queue = rides.data ?? []; const settings = config.data;
  return <Dashboard eyebrow="Operations" title="Keep scheduled trips dependable" description="Review exceptions, confirm coverage and manage the business network.">
    <nav className="app-nav dashboard-wide"><Link href="/admin/dispatch">Dispatch</Link><a href="#verification">Verification</a><a href="#backup">Backup readiness</a><a href="#subscriptions">Subscriptions</a><a href="#configuration">Configuration</a><a href="#audit">Audit</a></nav>
    {alerts.error && <p className="notice notice-error dashboard-wide" role="alert">{alerts.error}</p>}{alerts.message && <p className="notice notice-success dashboard-wide" role="status">{alerts.message}</p>}
    <DashboardCard title="Booking exceptions"><p>{queue.filter(ride => ['requested','searching','offered'].includes(ride.status)).length} unassigned · {queue.filter(ride => ['driver_en_route','driver_arrived','trip_started'].includes(ride.status)).length} active trips</p><p>{queue.filter(ride => ride.status === 'no_show').length} no-shows · {(safety.data ?? []).length} open safety reports</p><Link href="/admin/dispatch">Open dispatch queue</Link></DashboardCard>
    <DashboardCard title="Network readiness"><p>{(drivers.data ?? []).filter(driver => driver.online).length} drivers available · {(drivers.data ?? []).filter(driver => driver.verification_status === 'under_review').length} awaiting review</p><p>{(orgs.data ?? []).filter(org => org.kind === 'fleet').length} fleets · {(orgs.data ?? []).filter(org => org.kind === 'partner').length} partners · {(orgs.data ?? []).filter(org => org.kind === 'corporate').length} corporate accounts</p><Link href="/organizations">Business accounts</Link></DashboardCard>
    <section className="dashboard-wide"><h2>Upcoming and active bookings</h2>{queue.length ? <div className="table-scroll"><table><thead><tr><th>Ride</th><th>Schedule</th><th>Status</th></tr></thead><tbody>{queue.map(ride => <tr key={ride.id}><td>{ride.pickup_address}<br />{ride.dropoff_address}<small className="muted wrap-anywhere">{ride.id}</small></td><td>{dateTime(ride.scheduled_at)}</td><td>{ride.status.replaceAll('_',' ')}</td></tr>)}</tbody></table></div> : <p className="large-empty compact-empty">No booking exceptions right now.</p>}</section>
    <section className="dashboard-card dashboard-wide" id="verification"><h2>Driver verification</h2><p>Review driver and vehicle documents before approval. Expired documents cannot be approved.</p>{(drivers.data ?? []).map(driver => <details key={driver.id}><summary>{driver.id} · {driver.verification_status} · {driver.online ? 'Available' : 'Offline'}</summary><Link href={`/admin/drivers/${driver.id}`}>Review private documents</Link><form action={reviewDriver} className="compact-form"><input name="driver_id" type="hidden" value={driver.id} /><label>Decision<select name="decision"><option value="verified">Approve verification</option><option value="rejected">Reject application</option><option value="suspended">Suspend driver</option></select></label><label>Review reason<input name="reason" maxLength={1000} required /></label><SubmitButton pendingLabel="Saving review…">Record review</SubmitButton></form></details>)}</section>
    <section className="dashboard-card" id="backup"><h2>Backup driver readiness</h2><p>Confirmation window: {settings.scheduled_confirmation_hours} hours before pickup. Operations checks readiness and activates backups manually.</p>{(backups.data ?? []).map(backup => <article key={backup.id}><p className="wrap-anywhere">Ride {backup.ride_request_id}<br />Driver {backup.driver_id}</p><ConfirmForm action={activateBackup} message="Activate this backup and replace the primary driver?"><input type="hidden" name="ride_id" value={backup.ride_request_id} /><SubmitButton pendingLabel="Activating…">Activate backup</SubmitButton></ConfirmForm></article>)}<details><summary>Reserve eligible backup</summary><form action={setBackup} className="compact-form"><label>Ride ID<input name="ride_id" required /></label><label>Driver ID<input name="driver_id" required /></label><label>Vehicle ID<input name="vehicle_id" required /></label><SubmitButton pendingLabel="Reserving…">Reserve backup</SubmitButton></form></details></section>
    <section className="dashboard-card"><h2>Safety reports</h2>{(safety.data ?? []).length ? (safety.data ?? []).map(report => <details key={report.id}><summary>{report.category} · {report.status} · {dateTime(report.created_at)}</summary><p>{report.details}</p><form action={resolveSafety} className="compact-form"><input type="hidden" name="report_id" value={report.id} /><label>Review state<select name="status"><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option></select></label><label>Operations note<textarea name="note" required maxLength={2000} /></label><SubmitButton pendingLabel="Saving…">Save review</SubmitButton></form></details>) : <p>No open safety reports.</p>}</section>
    <section className="dashboard-card dashboard-wide" id="subscriptions"><h2>Business subscriptions</h2><div className="table-scroll"><table><thead><tr><th>Business</th><th>Plan</th><th>Status</th><th>Expiration</th><th>Billing</th></tr></thead><tbody>{(subscriptions.data ?? []).map(sub => <tr key={sub.id}><td>{orgs.data?.find(org => org.id === sub.organization_id)?.name ?? sub.organization_id}</td><td>{sub.plan_id}</td><td>{sub.status}</td><td>{dateTime(sub.expires_at)}</td><td>{sub.billing_status}</td></tr>)}</tbody></table></div><details><summary>Activate, extend, cancel or change plan</summary><form action={manageSubscription} className="compact-form"><label>Business<select name="organization_id" required>{(orgs.data ?? []).map(org => <option key={org.id} value={org.id}>{org.name} · {org.kind}</option>)}</select></label><label>Plan<select name="plan_id" required>{(plans.data ?? []).map(plan => <option key={plan.id} value={plan.id}>{plan.audience} · {plan.display_name}</option>)}</select></label><div className="form-grid"><label>Status<select name="status">{['trial','active','past_due','cancelled','expired'].map(status => <option key={status}>{status}</option>)}</select></label><label>Expiration (Philippines)<input type="date" name="expires_at" required /></label><label>Manual billing<select name="billing_status"><option value="manual_due">Manual payment due</option><option value="settled">Settled</option><option value="waived">Waived</option></select></label></div><SubmitButton pendingLabel="Updating…">Update subscription</SubmitButton></form></details></section>
    <section className="dashboard-card" id="configuration"><h2>Application configuration</h2><form action={updateConfiguration} className="compact-form"><label>Driver platform commission (%)<input type="number" name="driver_commission_percent" min={0} max={100} step="0.01" defaultValue={settings.driver_commission_percent} required /></label><label>Matching radius (km)<input type="number" name="default_matching_radius_km" min={1} max={200} defaultValue={settings.default_matching_radius_km} required /></label><label>Offer timeout (seconds)<input type="number" name="offer_timeout_seconds" min={30} max={600} defaultValue={settings.offer_timeout_seconds} required /></label><label>Confirmation window (hours)<input type="number" name="scheduled_confirmation_hours" min={1} max={24} defaultValue={settings.scheduled_confirmation_hours} required /></label><label>Local estimated speed (km/h)<input type="number" name="mock_route_speed_kph" min={5} max={120} defaultValue={settings.mock_route_speed_kph} required /></label><details><summary>Matching weights</summary>{['distance','reliability','going_home','return_trip','idle','preferences'].map(key=><label key={key}>{key.replaceAll('_',' ')}<input name={`weight_${key}`} type="number" min={0} max={1000} required defaultValue={settings.matching_weights[key]} /></label>)}</details><label className="check-label"><input type="checkbox" name="backup_driver_enabled" defaultChecked={settings.backup_driver_enabled} /> Enable backup reservations</label><SubmitButton pendingLabel="Saving…">Save configuration</SubmitButton></form></section>
    <section className="dashboard-card"><h2>Demo payment</h2>{process.env.HATIDONE_DEMO_MODE === 'true' && settings.demo_mode && settings.mock_payment_enabled ? <><p className="notice">DEMO PAYMENT · No money is collected or refunded.</p><form action={simulatePayment} className="compact-form"><input type="hidden" name="event_id" value={randomUUID()} /><label>Booking ID<input name="ride_id" required /></label><label>Simulated status<select name="status">{['pending','paid','failed','refunded'].map(status => <option key={status}>{status}</option>)}</select></label><SubmitButton pendingLabel="Simulating…">Record demo payment</SubmitButton></form></> : <p>Demo payments are disabled. Cash remains available. Enable only in an explicitly configured demo environment.</p>}</section>
    <section className="dashboard-wide" id="audit"><h2>Recent audit events</h2><div className="table-scroll"><table><thead><tr><th>Action</th><th>Entity</th><th>Time</th></tr></thead><tbody>{(audits.data ?? []).map(event => <tr key={event.id}><td>{event.action.replaceAll('_',' ')}</td><td>{event.entity_type}</td><td>{dateTime(event.created_at)}</td></tr>)}</tbody></table></div></section>
  </Dashboard>;
}
