import { useEffect, useRef, useState } from 'react';
import { Text } from 'react-native';
import { randomUUID } from 'expo-crypto';
import { useAuth } from './auth';
import { useResource } from './resource';
import { Button, Card, Field, Heading, Muted, Notice, dateTime } from './ui';
interface Message { id: string; sender_user_id: string; body: string; created_at: string }
export function RideChat({ rideRequestId }: { rideRequestId: string }) {
  const { client, session } = useAuth(); const [body, setBody] = useState(''); const [sending, setSending] = useState(false); const [error, setError] = useState(''); const pending = useRef<{ body: string; id: string } | null>(null);
  const resource = useResource(async () => { if (!client) return []; const result = await client.from('ride_messages').select('id,sender_user_id,body,created_at').eq('ride_request_id', rideRequestId).order('created_at', { ascending: false }).limit(100); if (result.error) throw new Error(result.error.message); const read = await client.rpc('mark_ride_messages_read', { p_ride_request_id: rideRequestId }); if (read.error) throw new Error(read.error.message); return (result.data as Message[]).reverse(); }, [client, rideRequestId]);
  useEffect(() => { if (!client) return; const channel = client.channel(`chat:${rideRequestId}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'ride_messages', filter: `ride_request_id=eq.${rideRequestId}` }, () => void resource.reload()).subscribe(); const timer = setInterval(() => void resource.reload(), 15000); return () => { clearInterval(timer); void client.removeChannel(channel); }; }, [client, rideRequestId, resource.reload]);
  async function send() { if (!client || !body.trim() || sending) return; setSending(true); setError(''); const text = body.trim(); if (pending.current?.body !== text) pending.current = { body: text, id: randomUUID() }; try { const result = await client.rpc('send_ride_message', { p_ride_request_id: rideRequestId, p_body: text, p_client_message_id: pending.current.id }); if (result.error) throw new Error(result.error.message); pending.current = null; setBody(''); await resource.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Message not sent. Retry safely.'); } finally { setSending(false); } }
  return <Card><Heading>Trip messages</Heading><Muted>Only authorized trip participants can read this conversation.</Muted>{resource.loading && !resource.data && <Muted>Loading messages…</Muted>}{(resource.error || error) && <Notice tone="error">{error || resource.error}</Notice>}{resource.data?.length === 0 && <Muted>No messages yet. Coordinate your pickup here.</Muted>}{resource.data?.map(message => <Card key={message.id}><Muted>{message.sender_user_id === session?.user.id ? 'You' : 'Trip participant'} · {dateTime(message.created_at)}</Muted><Text selectable>{message.body}</Text></Card>)}<Field label="Message" placeholder="Confirm your pickup landmark…" value={body} onChangeText={setBody} multiline maxLength={2000} /><Button label="Send message" loading={sending} disabled={!body.trim()} onPress={() => void send()} /></Card>;
}
