import { randomUUID } from 'node:crypto';
import { DEMO_LOCATIONS } from '@hatidone/core';
import { SubmitButton } from './submit-button';
import { createTransport } from '@/app/(protected)/organizations/actions';
export function TransportForm({ organizationId, corporate }: { organizationId: string; corporate: boolean }) {
  return <form action={createTransport} className="compact-form"><input type="hidden" name="organization_id" value={organizationId} /><input type="hidden" name="client_request_id" value={randomUUID()} />
    <div className="form-grid"><label>Pickup address<input name="pickup_address" required maxLength={240} placeholder="Guest lobby / office entrance" /></label><label>Destination<input name="dropoff_address" required maxLength={240} /></label><label>Pickup latitude<input name="pickup_lat" type="number" required step="any" min={-90} max={90} /></label><label>Pickup longitude<input name="pickup_lng" type="number" required step="any" min={-180} max={180} /></label><label>Destination latitude<input name="dropoff_lat" type="number" required step="any" min={-90} max={90} /></label><label>Destination longitude<input name="dropoff_lng" type="number" required step="any" min={-180} max={180} /></label><label>Pickup time (Philippines)<input name="scheduled_at" type="datetime-local" required /></label><label>Passengers<input name="passenger_count" type="number" min={1} max={30} defaultValue={1} required /></label><label>Vehicle<select name="vehicle_type"><option value="sedan">Sedan</option><option value="suv">SUV</option><option value="van">Van</option><option value="motorcycle">Motorcycle</option></select></label><label>Service<select name="service_type"><option value="transfer">Airport / resort transfer</option><option value="scheduled">Scheduled ride</option><option value="local">Local ride</option></select></label><label>Route preference<select name="route_preference"><option value="fastest">Fastest</option><option value="avoid_tolls">Avoid tolls</option><option value="preferred_route">Discuss preferred route</option></select></label><label>Reservation / external reference<input name="external_reference" maxLength={120} /></label></div>
    {corporate && <><label>Authorized employee user ID (optional)<input name="passenger_id" placeholder="Leave empty to book for yourself" /></label><label>Ride purpose / cost center<input name="ride_purpose" maxLength={240} placeholder="Airport trip · Sales" /></label></>}
    <details><summary>Service area reference coordinates</summary><ul>{DEMO_LOCATIONS.map(location => <li key={location.id}>{location.label}: {location.coordinates?.latitude}, {location.coordinates?.longitude}</li>)}</ul></details>
    <p className="muted">Fare is calculated on the server after submission using a local straight-line estimate. Tolls and actual road routes remain unverified. No online payment is taken.</p><SubmitButton pendingLabel="Requesting…">Request transport</SubmitButton>
  </form>;
}
