import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Dashboard, DashboardCard } from '@/components/dashboard';
import { PartnerReferrals } from '@/components/partner-referrals';
import { FleetResources } from '@/components/fleet-resources';
import { CopyLink } from '@/components/copy-link';
import { TransportForm } from '@/components/transport-form';
import { SubmitButton } from '@/components/submit-button';
import { getOrganization, dateTime, money } from '@/lib/operations/data';
import { saveLocation, saveMember } from '../actions';
export default async function OrganizationPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; message?: string; status?: string }> }) {
  const { id } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(id)) notFound();
  const [result, alerts] = await Promise.all([getOrganization(id), searchParams]);
  if (!result) notFound();
  const { organization: org, rides, canManage, members, locations, subscription, plans } = result;
  const month = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit' }).format(new Date());
  const monthly = rides.filter(ride => ride.scheduled_at && new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Manila', year: 'numeric', month: '2-digit' }).format(new Date(ride.scheduled_at)) === month);
  const shown = alerts.status ? rides.filter(ride => ride.status === alerts.status) : rides;
  const plan = plans.find(item => item.id === subscription?.plan_id);
  return <Dashboard eyebrow={`${org.kind} mobility`} title={org.name} description="Coordinate scheduled transport, authorized riders and business records.">
    <nav className="app-nav dashboard-wide"><Link href="/organizations">All accounts</Link><a href="#rides">Schedule</a><a href="#request">Request transport</a><a href="#members">Members</a><a href="#locations">Locations</a><a href="#subscription">Subscription</a></nav>
    {alerts.error && <p className="notice notice-error dashboard-wide" role="alert">{alerts.error}</p>}{alerts.message && <p className="notice notice-success dashboard-wide" role="status">{alerts.message}</p>}
    <DashboardCard title="This month"><p>{monthly.length} rides · {monthly.filter(ride => ride.status === 'trip_completed').length} completed</p><p>{money(monthly.reduce((total, ride) => total + (ride.status === 'trip_completed' ? Number(ride.estimated_fare ?? 0) : 0), 0))} completed ride estimates</p><p className="muted">Planning summary from the latest 200 bookings. Final settlement is recorded manually.</p></DashboardCard>
    {org.kind === 'partner' && <DashboardCard title="Guest booking link"><CopyLink path={`/book?partner_id=${org.id}`} /></DashboardCard>}
    {org.kind === 'partner' && canManage && <PartnerReferrals id={id} />}
    {org.kind === 'fleet' && canManage && <FleetResources organizationId={id} admin={result.profile.role === 'admin'} />}
    <section className="dashboard-wide" id="rides"><div className="section-title-row"><h2>Guest / employee transport schedule</h2><form><label>Status<select name="status" defaultValue={alerts.status ?? ''}><option value="">All</option><option value="requested">Unassigned</option><option value="assigned">Assigned</option><option value="trip_completed">Completed</option><option value="passenger_cancelled">Cancelled</option></select></label><button className="button button-secondary">Filter</button></form></div>
      {shown.length ? <div className="table-scroll"><table><thead><tr><th>Pickup / destination</th><th>Philippine schedule</th><th>Status</th><th>Passengers</th><th>Estimated fare</th><th>Reference / purpose</th></tr></thead><tbody>{shown.map(ride => <tr key={ride.id}><td>{ride.passenger_id===result.profile.id && result.profile.role==='passenger' ? <Link href={`/booking/${ride.id}`}>{ride.pickup_address}</Link> : ride.pickup_address}<br /><span className="muted">{ride.dropoff_address}</span></td><td>{dateTime(ride.scheduled_at)}</td><td>{ride.status.replaceAll('_', ' ')}</td><td>{ride.passenger_count}</td><td>{money(ride.estimated_fare)}</td><td>{ride.external_reference || ride.ride_purpose || '—'}<small className="wrap-anywhere">{ride.id}</small></td></tr>)}</tbody></table></div> : <p className="large-empty compact-empty">No rides match this view. Create a transport request below.</p>}</section>
    <section className="dashboard-card dashboard-wide" id="request"><h2>Request {org.kind === 'corporate' ? 'employee' : 'guest'} transport</h2>{canManage ? <TransportForm organizationId={id} corporate={org.kind === 'corporate'} /> : <p>Ask a business account manager to arrange your transport. Your personal rides remain available in the passenger booking flow.</p>}</section>
    <section className="dashboard-card" id="members"><h2>Authorized members</h2>{members.length ? <ul className="record-list">{members.map(member => <li key={member.id}><span className="wrap-anywhere">{member.user_id}</span><br />{member.member_role} · {member.status}</li>)}</ul> : <p>No visible members.</p>}{canManage && <details><summary>Add or update member</summary><form action={saveMember} className="compact-form"><input type="hidden" name="organization_id" value={id} /><label>Registered member email<input name="email" type="email" required placeholder="employee@example.test" /></label><label>Access<select name="member_role"><option value="rider">Rider</option><option value="manager">Manager</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label><SubmitButton pendingLabel="Saving…">Save member</SubmitButton></form></details>}</section>
    <section className="dashboard-card" id="locations"><h2>Pickup locations</h2>{locations.length ? <ul>{locations.map(location => <li key={location.id}><strong>{location.label}</strong><p>{location.address}</p></li>)}</ul> : <p>No saved locations.</p>}{canManage && <details><summary>Add location</summary><form action={saveLocation} className="compact-form"><input type="hidden" name="organization_id" value={id} /><label>Label<input name="label" required maxLength={100} placeholder="Guest lobby" /></label><label>Address<input name="address" required maxLength={240} /></label><div className="form-grid"><label>Latitude<input name="latitude" required type="number" step="any" min={-90} max={90} /></label><label>Longitude<input name="longitude" required type="number" step="any" min={-180} max={180} /></label></div><SubmitButton pendingLabel="Saving…">Save location</SubmitButton></form></details>}</section>
    <section className="dashboard-card dashboard-wide" id="subscription"><h2>Subscription</h2>{subscription ? <><p>{plan?.display_name ?? subscription.plan_id} · {result.subscriptionExpired ? 'expired' : subscription.status.replaceAll('_', ' ')}</p><p>Renewal / expiration: {dateTime(subscription.expires_at)} · Billing: {subscription.billing_status.replaceAll('_', ' ')}</p><ul>{(plan?.features ?? []).map(feature => <li key={feature}>{feature}</li>)}</ul></> : <p>No subscription activated yet. Operations can activate a plan manually.</p>}<p className="muted">No recurring card charge is enabled. Contact operations for plan changes and billing.</p></section>
  </Dashboard>;
}
